name: GitHub Actions Maven Build
run-name: ${{ github.actor }} is testing Maven Build 🚀

on: [push]

jobs:
  Maven-Build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - run: echo "⚙️ JDK 21 has been set up."

      - name: List Project Files
        run: |
            pwd
            ls -R
      - name: Change Directory to Java and Build with Maven
        run: |
          mvn clean install
      - run: echo "✅ Maven build completed."

      - name: Run Tests
        run: |
          mvn test
      - run: echo "Tests have been executed."

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: Java/target/surefire-reports/

      - run: echo "This job's status is ${{ job.status }}."
